### ISSUE TITLE
sessions are not being terminated when a user signs out

### ISSUE THREAD

**Issue by engerm** [john/drive.vote#319]
Description:
Sessions are not being terminated when a user signs out of the browsers.

NOTE: This has security impact

Version:
unknown
https://dev.drive.vote

Steps:
Configure browser to use a proxy, such as Burp.

Log in as admin

Navigate to admin page

Create a new ride by navigating to Rides > New Ride

Fill out form, calling name "Browser test"

Click Save

Navigate back to Rides page to ensure ride has been added.

Switch Burp. Locate request and send to Repeater.

In Repeater, change name from "Browser+test" to "Burp+test"

Send request

In browser, refresh Rides page to ensure ride has been added.

In browser, sign out by clicking "Sign out"

In Burp Repeater, change name from "Browser+test" to "Burp+test+signed+out"

Send request

In browser, log back in as an administrator

Got to Rides pages by navigating to admin > Rides

[note the signed out request exists]

Actual Results:

Sessions are note being terminated when a user signs out.

Expected Results:
1) Sessions would be terminated when a user signs out
2) An terminated session would be unable to perform a request that requires a valid session

**Comment by leewaa** [comment]
Even if this is not a threat this should not be happening. When you destroy the session then the cookie should be destroyed along with it and not be hanging around. This should be a part of the devise gem instead of the users' of the gem. Having to introduce middleware or some sort of dummy cache to "fix" this issue isn't all that nice.

Question: What use case is there to keep the session cookie once the session has been destroyed?

**Comment by heaven** [comment]
The session is not destroyed on sign out, only the corresponding `warden.user` key deleted, but the session still keeps `_csrf_token` so if you have more tabs open the forms there wouldn't stop working. So keeping the session is better. Additionally, you may have multiple scopes (for example we have `Member < User` and `Employee < User` models) which can log in/out independently but they do share the same session.
