### ISSUE TITLE
Driver app should show the date/time the ride was scheduled

### ISSUE THREAD

**Issue by engerm** [john/drive.vote#556]
Description:

This is an enhancement request to show to date/time the rider should be picked up. This will be help the driver plan route.

Time could either show up on the Selection page or the Accept Ride page. Also could show the puck up date/time on all the pages including the Pick Up page and the Complete page.

Version:
unknown
https://dev.drive.vote

Steps:

Actual Results:

Expected Results:

**Comment by johnkaplantech** [comment]
Hey John - have started investigating & have a few questions:
Looks like there is no concept of date/time in the javascript ride object yet. Does this need to be added for both entry and display, or is it already entered somewhere I don't see and just needs to be displayed?
I can't find the word "Selection" referenced outside of node_modules - is this called something else in the code or am I looking in the wrong place?
I do see RidePropTypes that seems to define the ride object - am I right this is the place where the date/time would go?
RidePropTypes is referenced in ActiveRide, PendingRide, and PendingRideDetail - is this where this code would go?
I'm also missing how a ride gets persisted & read from DB - where would I find that code?

**Comment by john** [comment]
HI @johnkaplantech, apologies for the slow reply, just saw this.

Last question first: there's an API called by the React app. The API itself is in the same codebase as everything else and can be found at:
https://github.com/john/drive.vote/tree/master/app/controllers/api

On the React side, I know some API calls (though not sure if all) are made from:
https://github.com/john/drive.vote/blob/master/app/javascript/driving/actions/actionCreators.js

@mcamis can best answer everything else--if you want to talk through anything with me though, please ping me on Slack or by email (john@fnnny.com). Thanks.

**Comment by mcamis** [comment]
👋 
Sorry @johnkaplantech  I've been out of commission.

> Looks like there is no concept of date/time in the javascript ride object yet. Does this need to be added for both entry and display, or is it already entered somewhere I don't see and just needs to be displayed?

We're already receiving the `pickup_at` field for rides returned from the API, it's not being referenced anywhere in the JS app currently though.


> I can't find the word "Selection" referenced outside of node_modules - is this called something else in the code or am I looking in the wrong place?

"Selection" in this context refers to the output of [`WaitingRidesContainer`](https://github.com/john/drive.vote/blob/master/app/javascript/driving/containers/WaitingRidesContainer.js).


> I do see RidePropTypes that seems to define the ride object - am I right this is the place where the date/time would go?

This is an (incomplete) mirror of the ride data model as we use it in the driver app, so this will need to be updated as well


>RidePropTypes is referenced in ActiveRide, PendingRide, and PendingRideDetail - is this where this code would go?

Yep! Since the data is already included with each "ride" object, this might be just be as simple as formatting the time and updating each ride-related component you mentioned(`PendingRide`, `PendingRideDetail` and `ActiveRide`).

Also feel free to ask me about any of this on Slack!

**Comment by john** [comment]
@johnkaplantech closed with #1005
